# Generated by Django 5.0.2 on 2024-02-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="ratings_count",
            field=models.IntegerField(null=True),
        ),
    ]
