# Generated by Django 5.0.2 on 2024-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_average_rating_alter_book_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="thumbnail",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
