# Generated by Django 5.0.2 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.TextField(null=True),
        ),
    ]
